// I57: agent instruction files tell the truth. What is a wrong design-system name, and what is not.
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { findSteeringFiles, steeringTruth, steeringFindings, steeringLine } from '../steering-check.mjs';
import { makeFixture } from './helpers.mjs';

const truth = steeringTruth({
  catalog: { components: {
    chip: { props: { Size: { type: 'enum', values: ['M', 'L'], codeName: 'size' }, Icon: { type: 'enum', values: ['False', 'True'], codeName: 'icon' } } },
    badge: { props: { Tone: { type: 'enum', values: ['Neutral', 'Success', 'Warning', 'Danger'], codeName: 'tone' } } },
    button: { props: {} },
  } },
  api: { badge: { props: { tone: { options: ['neutral', 'success', 'warning', 'danger'] } } } },
  cssVars: ['--radii-chip', '--padding-s', '--button-background'],
  tokenNames: ['radii/chip', 'surface/page/color', 'padding/s'],
});
const find = (text) => steeringFindings(text, truth).map((f) => [f.line, f.kind, f.found, f.want ?? null]);

test('a wrong prop value, in code or in a listed set, with the value the system has', () => {
  assert.deepEqual(find('Status tones: `tone`: success | warning | error'), [[1, 'prop value', 'tone="error"', 'tone="danger"']]);
  assert.deepEqual(find('<Badge tone="error">Failed</Badge>'), [[1, 'prop value', 'tone="error"', 'tone="danger"']]);
  assert.deepEqual(find('<Badge tone="danger" />, tone: neutral | success | warning | danger'), []);
  assert.deepEqual(find('<Chip size="md">'), [[1, 'prop value', 'size="md"', 'size="M"']]);   // md means M, but the name is not M
  assert.deepEqual(find('<Chip size="xl">'), [[1, 'prop value', 'size="xl"', null]]);
  assert.match(steeringLine('AGENTS.md', steeringFindings('<Chip size="xl">', truth)[0]), /^AGENTS\.md:1  size="xl" is not a value this prop takes; the system has M, L$/);
  assert.deepEqual(find('<Chip icon="yes">'), []);                    // booleans are not a vocabulary
  assert.deepEqual(find('Pick a size: small or large.'), [[1, 'prop value', 'size="small"', null], [1, 'prop value', 'size="large"', 'size="L"']]);   // no small; large is named L
  assert.deepEqual(find('The size: keep it readable, and the state of the art moves fast.'), []);   // prose, no value of the prop
});

test('a prop name written in code other than the way the code writes it', () => {
  assert.deepEqual(find('<Badge Tone="danger">'), [[1, 'prop name', 'Tone', 'tone']]);
  assert.deepEqual(find('<Badge TONE="error">'), [[1, 'prop name', 'TONE', 'tone'], [1, 'prop value', 'TONE="error"', 'tone="danger"']]);
  assert.deepEqual(find('The Tone: neutral or danger. Size matters.'), []);   // prose is not code
  assert.match(steeringLine('AGENTS.md', steeringFindings('<Badge Tone="danger">', truth)[0]), /^AGENTS\.md:1  Tone is not the prop's name as the code writes it; the system has tone$/);
});

test('ghost variables and tokens; command flags, URLs and file paths are left alone', () => {
  assert.deepEqual(find('Round it with var(--radii-chipp).'), [[1, 'variable', '--radii-chipp', '--radii-chip']]);
  assert.deepEqual(find('Use `--radii-pill` for pills.'), [[1, 'variable', '--radii-pill', null]]);   // too far from any real one to guess
  assert.deepEqual(find('Run rms-figma-code-parity --component chip, or --radii-chip in a sentence.'), []);
  assert.deepEqual(find('Token radii/chipz is the chip radius.'), [[1, 'token', 'radii/chipz', 'radii/chip']]);
  assert.deepEqual(find('The chip radius token is radii/chipz.'), [[1, 'token', 'radii/chipz', 'radii/chip']]);   // the sentence's full stop
  assert.deepEqual(find('See https://example.com/radii/chipz and src/radii/whatever.css; surface/page is fine.'), []);
  assert.deepEqual(find('Pick the swatch by surface/hex or by name.'), []);                    // prose "a or b", no near token
  assert.deepEqual(find('Use `surface/hover/color` for hover.'), [[1, 'token', 'surface/hover/color', null]]);   // written as code
});

test('a component that is not in the catalog, only in a file about this system', () => {
  assert.deepEqual(find('<Chips size="M" /> and <Button />'), [[1, 'component', '<Chips>', 'chip']]);
  assert.deepEqual(find('<Tooltip /> next to <Chip />'), [[1, 'component', '<Tooltip>', null]]);
  assert.deepEqual(find('Wrap the app in <Provider> and <Fragment> with <Chip />'), []);
  assert.deepEqual(find('<Modal /> <Drawer />'), []);                   // not about this system: no opinion
});

test('instruction files are found on their own; the parity\'s generated files never are', () => {
  const dir = makeFixture({
    'AGENTS.md': 'Use <Chip />.',
    '.cursor/rules/ds.mdc': 'tone: error',
    '.github/copilot-instructions.md': 'x',
    'llms.txt': '# Design system — machine-readable index\n\n> Generated by rms-parity from Figma + code.',
    'contracts/llms.txt': 'x',
    'docs/notes.md': 'not an instruction file',
    'skills/ds/SKILL.md': 'y',
  });
  assert.deepEqual(findSteeringFiles(dir, { skip: ['contracts'] }).map((f) => f.file).sort(),
    ['.cursor/rules/ds.mdc', '.github/copilot-instructions.md', 'AGENTS.md', 'skills/ds/SKILL.md']);
});

test('in a real run on the demo design system: wrong names are listed, a correct file is said to be correct', async () => {
  const { cpSync, mkdtempSync, writeFileSync, mkdirSync } = await import('node:fs');
  const { join, dirname } = await import('node:path');
  const { tmpdir } = await import('node:os');
  const { spawnSync, execFileSync } = await import('node:child_process');
  const { fileURLToPath } = await import('node:url');
  const ENGINE = dirname(dirname(fileURLToPath(import.meta.url)));
  const run = (files) => {
    const dir = mkdtempSync(join(tmpdir(), 'steer-'));
    cpSync(join(ENGINE, 'test', 'fixtures', 'demo-ds'), dir, { recursive: true, filter: (p) => !/expected-report/.test(p) });
    for (const [f, text] of Object.entries(files)) { mkdirSync(dirname(join(dir, f)), { recursive: true }); writeFileSync(join(dir, f), text); }
    const env = { GIT_AUTHOR_NAME: 't', GIT_AUTHOR_EMAIL: 't@e', GIT_COMMITTER_NAME: 't', GIT_COMMITTER_EMAIL: 't@e' };
    execFileSync('git', ['init', '-q'], { cwd: dir }); execFileSync('git', ['add', '-A'], { cwd: dir }); execFileSync('git', ['commit', '-qm', 'x'], { cwd: dir, env: { ...process.env, ...env } });
    const r = spawnSync(process.execPath, [join(ENGINE, 'audit.mjs'), '--static'], { cwd: dir, encoding: 'utf8', env: { ...process.env, CI: '1', NO_COLOR: '1', PARITY_NO_AUTO_UPDATE: '1' }, timeout: 300000 });
    return r.stdout + r.stderr;
  };
  const bad = run({ 'AGENTS.md': 'Use <Chip size="XL"> next to <Button />.\nRound it with var(--radii-chipp).\nThe radius token is radii/chipz.\nRun rms-figma-code-parity --component chip.\n' });
  const saved = join(tmpdir(), `steer-run-${process.pid}.txt`); writeFileSync(saved, bad);
  assert.match(bad, /🧭 Agent instruction files: 3 design-system names that do not exist \(AGENTS\.md\)/, `full output in ${saved}`);
  assert.match(bad, /AGENTS\.md:1  size="XL" is not a value this prop takes; the system has M, L/);
  assert.match(bad, /AGENTS\.md:2  --radii-chipp is not a declared CSS variable; the system has --radii-chip/);
  assert.match(bad, /AGENTS\.md:3  radii\/chipz is not a token; the system has radii\/chip/);
  const good = run({ 'CLAUDE.md': 'Use <Chip size="L" /> with var(--radii-chip); the token is radii/chip.\n' });
  assert.match(good, /🧭 Agent instruction files \(CLAUDE\.md\): every design-system name they state exists\./);
});

test('I63: a file about the design system that only says what not to use', async () => {
  const { mandateOf } = await import('../steering-check.mjs');
  const comps = ['chip', 'button', 'badge'];
  assert.equal(mandateOf('# Agents\nNever build your own chip. Avoid inline styles in the design system.', comps).onlyForbids, true);
  assert.equal(mandateOf('# Agents\nThe design system is installed: use its components (Chip, Button). Never build your own chip.', comps).onlyForbids, false);
  assert.equal(mandateOf('# Agentes\nO sistema de design está instalado: usa os componentes dele. Nunca cries o teu próprio chip.', comps).onlyForbids, false);
  assert.equal(mandateOf('# Project\nNever push on Fridays. Run npm test first.', comps).onlyForbids, false);   // not about the system
});
