// compile-check.mjs - generated UI type-checks against the design system's own props (idea I66).
//
// S29: only 10 of 55 guided generations compiled against the published types, and the errors clustered on a few
// names: a value a prop does not take (direction="column" where it takes vertical or horizontal), a string into a
// number prop. So a generated .tsx/.jsx candidate is type-checked with the TypeScript compiler against types built
// from the catalog (contracts/catalog.json), written the way the code writes them: each prop's code name, each
// enum's code values (Figma's when the code has none), True/False as a boolean. Only what the design system
// states is checked: any other prop is allowed (the catalog is not the whole API), imports are removed and names
// the candidate imports from elsewhere are never reported, so an error is always about a design-system component.
// Needs tsc (the project's own typescript, or tsc on the PATH); without it the check says so and is skipped.
import { writeFileSync, mkdirSync, rmSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { spawnSync } from 'node:child_process';
import { createRequire } from 'node:module';
import { OUT_DIR } from './names.mjs';

const pascal = (s) => String(s).replace(/(^|[-_\s]+)(\w)/g, (_, __, c) => c.toUpperCase());
const ident = (s) => /^[A-Za-z_$][\w$]*$/.test(s) ? s : JSON.stringify(s);
const isBool = (vals) => vals.length > 0 && vals.every((v) => /^(true|false)$/i.test(String(v)));

// catalog → declarations: one `declare function Chip(props: {...}): any` per component, and a JSX namespace that
// lets every HTML element through.
export function compileShim(catalog = {}) {
  const out = ['// Generated by rms-design-system-engine for the compile check. Types from contracts/catalog.json.',
    'declare namespace JSX { interface IntrinsicElements { [tag: string]: any } interface Element {} interface ElementChildrenAttribute { children: {} } }'];
  for (const [name, c] of Object.entries(catalog.components ?? {})) {
    const props = [];
    for (const [figma, p] of Object.entries(c.props ?? {})) {
      const key = p.codeName ?? figma;
      const vals = (p.codeValues ?? p.values ?? []).map(String);
      const type = p.type === 'enum' ? (isBool(vals) ? 'boolean' : vals.map((v) => JSON.stringify(v)).join(' | ') || 'string')
        : p.type === 'text' ? 'string' : p.type === 'boolean' ? 'boolean' : p.type === 'number' ? 'number' : 'any';
      props.push(`${ident(key)}?: ${type};`);
    }
    out.push(`declare function ${pascal(name)}(props: { ${props.join(' ')} children?: any; [other: string]: unknown }): any;`);
  }
  return out.join('\n') + '\n';
}

// The compiler: the project's typescript first, then tsc on the PATH. → { cmd, args } or null.
export function findTsc(ROOT) {
  try {
    const req = createRequire(join(resolve(ROOT), 'package.json'));
    return { cmd: process.execPath, args: [req.resolve('typescript/bin/tsc')] };
  } catch { /* not in the project */ }
  const which = spawnSync('/bin/sh', ['-c', 'command -v tsc'], { encoding: 'utf8' });
  return which.status === 0 && which.stdout.trim() ? { cmd: which.stdout.trim(), args: [] } : null;
}

// The candidate as the compiler reads it: imports and re-exports removed (their names are declared, so a
// component comes from the shim and anything else is `any`).
export function prepare(code, catalog = {}) {
  const src = String(code ?? '');
  const comps = Object.keys(catalog.components ?? {}).map(pascal);
  const norm = (x) => String(x).toLowerCase().replace(/[^a-z0-9]/g, '');
  // The code's own export name for a component (HbBadge for badge): a short library prefix, like the edit check.
  const componentOf = (n) => comps.find((c) => norm(c) === norm(n)) ?? comps.find((c) => norm(n).endsWith(norm(c)) && /^[a-z]{1,4}$/.test(norm(n).slice(0, -norm(c).length)));
  const imported = new Set();
  // Imports become blank lines, so every line keeps its number.
  const blank = (m) => m.replace(/[^\n]/g, '');
  const body = src.replace(/^[ \t]*import\s+([^;]*?)\s+from\s+["'][^"']+["'];?[ \t]*$/gm, (m, what) => {
    for (const x of what.matchAll(/([A-Za-z_$][\w$]*)(?:\s+as\s+([A-Za-z_$][\w$]*))?/g)) if (x[1] !== 'type') imported.add(x[2] ?? x[1]);
    return blank(m);
  }).replace(/^[ \t]*import\s+["'][^"']+["'];?[ \t]*$/gm, blank);
  const decl = [];
  for (const n of imported) {
    if (n === 'React' || comps.includes(n)) continue;
    const c = componentOf(n);
    decl.push(c ? `declare const ${n}: typeof ${c};` : `declare const ${n}: any;`);
  }
  if (!imported.has('React') && /\bReact\b/.test(body)) decl.push('declare const React: any;');
  if (imported.has('React')) decl.push('declare const React: any;');
  // Declarations go on the first line, so line numbers stay the candidate's own.
  const lines = body.split('\n');
  lines[0] = `${decl.join(' ')} ${lines[0]}`;
  return lines.join('\n');
}

// tsc output → [{ line, code, message }] for the candidate file only, lines counted in the candidate as written.
export function parseTscOutput(text, file, offset = 0) {
  const out = [];
  for (const m of String(text ?? '').matchAll(/^(.+?)\((\d+),(\d+)\): error (TS\d+): (.+(?:\n {2,}.+)*)$/gm)) {
    if (!m[1].endsWith(file)) continue;
    out.push({ line: Number(m[2]) - offset, code: m[4], message: m[5].replace(/\s*\n\s*/g, ' ').trim() });
  }
  return out;
}

// One candidate → { ran: true, errors } or { ran: false, why }.
export function typeErrors(code, catalog, { ROOT = process.cwd(), dir = join(ROOT, OUT_DIR, 'compile'), id = 'candidate', tsc = findTsc(ROOT), ext = 'tsx' } = {}) {
  if (!tsc) return { ran: false, why: 'no TypeScript compiler (install typescript in the project, or tsc on the PATH)' };
  if (!Object.keys(catalog?.components ?? {}).length) return { ran: false, why: 'no contracts/catalog.json yet (run the audit once to write it)' };
  mkdirSync(dir, { recursive: true });
  const prepared = prepare(code, catalog);
  const file = `${id.replace(/[^\w-]/g, '_')}.${ext === 'jsx' ? 'tsx' : ext}`;
  writeFileSync(join(dir, 'design-system-engine-shim.d.ts'), compileShim(catalog));
  writeFileSync(join(dir, file), prepared);
  writeFileSync(join(dir, 'tsconfig.json'), JSON.stringify({ compilerOptions: { noEmit: true, jsx: 'preserve', strict: false, noImplicitAny: false, skipLibCheck: true, target: 'es2022', module: 'esnext', moduleResolution: 'bundler', types: [], lib: ['es2022', 'dom'] }, files: ['design-system-engine-shim.d.ts', file] }, null, 2));
  const r = spawnSync(tsc.cmd, [...tsc.args, '-p', join(dir, 'tsconfig.json'), '--pretty', 'false'], { encoding: 'utf8', timeout: 60000 });
  if (r.error) return { ran: false, why: `tsc did not run: ${r.error.message}` };
  const errors = parseTscOutput(`${r.stdout}\n${r.stderr}`, file);
  try { rmSync(join(dir, file)); } catch { /* left for a look */ }
  return { ran: true, errors };
}

export function typeErrorLine(e) {
  return `line ${e.line}: ${e.message}`;
}

export const COMPILE_EXTS = new Set(['tsx', 'jsx', 'ts']);
export const compileTarget = (ext) => COMPILE_EXTS.has(String(ext).toLowerCase());
