// steering-check.mjs - agent instruction files tell the truth (idea I57).
//
// The prose files a team writes for coding agents (AGENTS.md, CLAUDE.md, DESIGN.md, Cursor and Copilot
// rules, skills) state design-system names from memory. When one is wrong, every agent that reads it builds
// the wrong thing: one wrong prop value in an AGENTS.md (`error` where the library says `danger`) caused ten of
// nineteen hard failures in ninety generations in Southleft's benchmark, and none in bare runs. This finds
// those files on its own and checks each name they state against what the parity already knows:
//   • a CSS variable in var(--x), or written like one of the design system's own, that is declared nowhere;
//   • a token path (radii/chip, surface/page/color) that is not a token;
//   • a component tag (<Chip>) that is not in the catalog, in a file that is about this design system;
//   • a prop value that neither Figma nor the code names exactly (tone="error", size="md" for M), with the
//     value it corresponds to. A different name for the same value is still a different name;
//   • a prop name written in code (Tone="danger") other than the way the code writes it (tone).
// Advisory, never fails. The parity's own generated files (contracts, llms.txt) are never read.
import { readFileSync, existsSync, readdirSync, statSync } from 'node:fs';
import { join, relative } from 'node:path';
import { norm, sizeGroup, counterpart } from './prop-vocabulary.mjs';

// Where agent instructions live. Files at these paths, and every .md / .mdc / .txt under the folders.
export const STEERING_FILES = ['AGENTS.md', 'CLAUDE.md', 'DESIGN.md', 'GEMINI.md', '.cursorrules', '.windsurfrules', '.github/copilot-instructions.md', 'llms.txt'];
export const STEERING_DIRS = ['.cursor/rules', '.github/instructions', '.claude/skills', '.claude/commands', '.agents', 'skills'];
const GENERATED = /Generated by rms-(?:figma-code-)?parity|generated by rms-parity/i;

export function findSteeringFiles(ROOT, { skip = [] } = {}) {
  const out = [];
  const skipAbs = skip.map((p) => join(ROOT, p));
  const take = (abs) => {
    if (skipAbs.some((s) => abs === s || abs.startsWith(s + '/'))) return;
    let text; try { text = readFileSync(abs, 'utf8'); } catch { return; }
    if (GENERATED.test(text.slice(0, 600))) return;   // the parity's own output is the truth, not a copy of it
    out.push({ file: relative(ROOT, abs), text });
  };
  for (const f of STEERING_FILES) if (existsSync(join(ROOT, f))) take(join(ROOT, f));
  const walk = (dir, depth) => {
    let names; try { names = readdirSync(dir); } catch { return; }
    for (const n of names) {
      const abs = join(dir, n);
      let st; try { st = statSync(abs); } catch { continue; }
      if (st.isDirectory()) { if (depth < 4 && n !== 'node_modules') walk(abs, depth + 1); }
      else if (/\.(md|mdc|txt)$/i.test(n)) take(abs);
    }
  };
  for (const d of STEERING_DIRS) if (existsSync(join(ROOT, d))) walk(join(ROOT, d), 0);
  return out;
}

function distance(a, b) {
  const m = a.length, n = b.length, d = Array.from({ length: m + 1 }, (_, i) => [i, ...Array(n).fill(0)]);
  for (let j = 1; j <= n; j++) d[0][j] = j;
  for (let i = 1; i <= m; i++) for (let j = 1; j <= n; j++) d[i][j] = Math.min(d[i - 1][j] + 1, d[i][j - 1] + 1, d[i - 1][j - 1] + (a[i - 1] === b[j - 1] ? 0 : 1));
  return d[m][n];
}
const closest = (word, list, max = 2) => {
  let best = null, bd = max + 1;
  for (const c of list) { const x = distance(word.toLowerCase(), c.toLowerCase()); if (x < bd) { bd = x; best = c; } }
  return best;
};

// The truth the parity already has, in the shape this check needs.
// catalog: contracts/catalog.json; api: the code capture's api ({ comp: { props: { name: { options } } } });
// cssVars: declared custom properties; tokenNames: token paths (surface/page/color, radii/chip).
export function steeringTruth({ catalog = {}, api = {}, cssVars = [], tokenNames = [] } = {}) {
  const components = Object.keys(catalog.components ?? {});
  const props = new Map();   // prop name (normalized) → { names:Set, code:Set, figma:Set, codeNames:Set }
  const add = (name, values, side) => {
    if (!name || !values?.length) return;
    if (values.every((v) => /^(true|false)$/i.test(String(v)))) return;   // booleans are never a vocabulary problem
    const k = norm(name);
    const e = props.get(k) ?? { names: new Set(), code: new Set(), figma: new Set(), codeNames: new Set() };
    e.names.add(name.toLowerCase()); for (const v of values) e[side].add(String(v));
    if (side === 'code') e.codeNames.add(name);
    props.set(k, e);
  };
  for (const c of Object.values(catalog.components ?? {})) {
    for (const [fig, p] of Object.entries(c.props ?? {})) {
      if (p.type !== 'enum') continue;
      add(fig, p.values, 'figma'); if (p.codeName) { add(p.codeName, p.values, 'figma'); props.get(norm(p.codeName))?.codeNames.add(p.codeName); }
    }
  }
  for (const c of Object.values(api ?? {})) for (const [name, p] of Object.entries(c?.props ?? {})) if (Array.isArray(p.options)) add(name, p.options, 'code');
  const vars = new Set(cssVars);
  const families = new Set([...vars].map((v) => v.replace(/^--/, '').split('-')[0]).filter(Boolean));
  const tokens = new Set(tokenNames);
  const tokenFamilies = new Set(tokenNames.map((t) => t.split('/')[0]).filter(Boolean));
  return { components, props, vars, families, tokens, tokenFamilies };
}

const IGNORE_TAGS = new Set(['Fragment', 'Suspense', 'StrictMode', 'Provider', 'App', 'Router', 'Route', 'Routes', 'Component', 'Story', 'Meta', 'Canvas', 'Props']);

// One file → [{ line, kind, found, want?, valid? }].
export function steeringFindings(text, truth) {
  const out = [];
  const lines = String(text ?? '').split('\n');
  const compNorm = new Map(truth.components.map((c) => [norm(c), c]));
  const tagsInFile = [...String(text).matchAll(/<([A-Z][A-Za-z0-9]+)/g)].map((m) => m[1]);
  const aboutThisSystem = tagsInFile.some((t) => compNorm.has(norm(t)));
  const seen = new Set();
  const push = (f) => { const k = `${f.line}|${f.kind}|${f.found}`; if (!seen.has(k)) { seen.add(k); out.push(f); } };
  lines.forEach((l, i) => {
    const line = i + 1;
    // CSS variables: inside var(), or a backticked --name of one of the system's own families.
    const varMentions = [...l.matchAll(/var\(\s*(--[\w-]+)/g)].map((m) => m[1])
      .concat([...l.matchAll(/`(--[a-z][\w-]*)`/g)].map((m) => m[1]).filter((v) => truth.families.has(v.slice(2).split('-')[0])));
    for (const v of varMentions) if (truth.vars.size && !truth.vars.has(v)) push({ line, kind: 'variable', found: v, want: closest(v, [...truth.vars], 3) });
    // Token paths of the system's own families, never inside a URL or a file path.
    if (truth.tokenFamilies.size) {
      const fam = [...truth.tokenFamilies].map((f) => f.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')).join('|');
      for (const m of l.matchAll(new RegExp(`(?<![\\w./:@-])((?:${fam})(?:/[\\w-]+)+)(?![\\w/-]|\\.\\w)`, 'g'))) {
        const t = m[1];
        const known = truth.tokens.has(t) || [...truth.tokens].some((k) => k.startsWith(t + '/') || k === `${t}/color`);
        if (known) continue;
        // In running prose "a/b" is often just "a or b": flag it when written as code, or when a real token is a near miss.
        const want = closest(t, [...truth.tokens], 2);   // a typo, not a different token
        if (l[m.index - 1] === '`' || want) push({ line, kind: 'token', found: t, want });
      }
    }
    // Component tags, only in a file that uses at least one of this system's components.
    if (aboutThisSystem && truth.components.length) {
      for (const m of l.matchAll(/<([A-Z][A-Za-z0-9]+)/g)) {
        const tag = m[1];
        if (IGNORE_TAGS.has(tag) || compNorm.has(norm(tag))) continue;
        const near = closest(norm(tag), [...compNorm.keys()], 2);
        push({ line, kind: 'component', found: `<${tag}>`, want: near ? compNorm.get(near) : null });
      }
    }
    // Prop values: name="value" in code, or a listed set (tone: success | warning | error) anchored by a real value.
    for (const p of truth.props.values()) {
      // The code's own values first: an agent writes code, so the suggestion is what the code accepts.
      const valid = [...new Set([...p.code, ...[...p.figma].filter((f) => ![...p.code].some((c) => norm(c) === norm(f)))])];
      // Only the exact name is right (letter case aside): md where the system says M is a naming difference,
      // reported with the value it corresponds to, never accepted.
      const ok = (v) => valid.some((x) => norm(x) === norm(v));
      const counterpartIn = (v) => counterpart(v, valid);
      const names = [...p.names].map((n) => n.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')).join('|');
      const flag = (name, v) => {
        if (ok(v) || /^(true|false|null|undefined)$/i.test(v)) return;
        const want = counterpartIn(v) || (sizeGroup(v) ? null : closest(v, valid, 2));   // xl is not a typo of L
        const as = [...p.codeNames].includes(name) || !p.codeNames.size ? name : [...p.codeNames][0];   // the suggestion uses the code's name
        push({ line, kind: 'prop value', found: `${name}="${v}"`, want: want ? `${as}="${want}"` : null, valid });
      };
      for (const m of l.matchAll(new RegExp(`(?<![\\w-])(${names})\\s*=\\s*\\{?\\s*["'\`]([\\w-]+)["'\`]`, 'gi'))) {
        // The prop's own name, as code writes it: Tone="danger" where the code has tone is a wrong name.
        const right = [...p.codeNames];
        if (right.length && !right.includes(m[1])) push({ line, kind: 'prop name', found: m[1], want: right[0] });
        flag(m[1], m[2]);
      }
      const list = l.match(new RegExp(`(?<![\\w-])\`?(${names})\`?\\s*[:=]\\s*([^.;()]+)`, 'i'));
      if (list && !/^\s*\{?\s*["'`]/.test(list[2])) {
        const items = list[2].split(/\s*(?:\||,|\/|\bor\b)\s*/).map((x) => x.trim().replace(/^[`"']|[`"']$/g, '')).filter((x) => /^[\w-]+$/.test(x)).slice(0, 12);
        if (items.length >= 2 && items.some((v) => ok(v) || counterpartIn(v))) for (const v of items) flag(list[1], v);
      }
    }
  });
  return out;
}

export function steeringLine(file, f) {
  const want = f.want ? `; the system has ${f.want}` : f.valid?.length ? `; the system has ${f.valid.join(', ')}` : '';
  const what = { variable: 'is not a declared CSS variable', token: 'is not a token', component: 'is not a component in the catalog', 'prop value': 'is not a value this prop takes', 'prop name': 'is not the prop\'s name as the code writes it' }[f.kind];
  return `${file}:${f.line}  ${f.found} ${what}${want}`;
}

// Says what to use, not only what not to use (idea I63). A public benchmark (S29) measured it: an AGENTS.md that
// listed what to avoid put 16 of 57 generations on the design system; one added sentence saying the package is
// installed and is the one to use, 43 of 55. A file about this design system that only forbids is noted.
const POSITIVE = /\b(use|uses|using|prefer|build (it |them )?with|import (it |them )?from|is installed|are installed|always use|usa|use-se|utiliza|usar|está instalad[oa]|estão instalad[oa]s|prefere)\b/i;
const NEGATIVE = /\b(don'?t|do not|never|avoid|no longer|não uses?|não utilize|nunca|evita|evitar)\b/i;
export function mandateOf(text, components = []) {
  const names = components.map((c) => String(c).toLowerCase()).filter((c) => c.length >= 3);
  const sentences = String(text ?? '').split(/(?<=[.!?])\s+|\n+/).map((s) => s.trim()).filter(Boolean);
  const about = (s) => /design[- ]system|component library|biblioteca de componentes|sistema de design/i.test(s)
    || names.some((n) => new RegExp(`(?<![\\w-])<?${n.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}s?\\b`, 'i').test(s));
  const relevant = sentences.filter(about);
  const negative = relevant.filter((s) => NEGATIVE.test(s)).length;
  const positive = relevant.filter((s) => POSITIVE.test(s) && !NEGATIVE.test(s)).length;
  return { about: relevant.length > 0, positive, negative, onlyForbids: negative > 0 && positive === 0 };
}
